public class Ex02 {
    public static void main(String[] args) {
        /*
            FAÇA UM PROGRAMA QUE DADO O SALARIO DE UM FUNCIONARIO (SEM OS DESCONTOS), VALOR DESEJADO DO EMPRESTIMO E QUANTIDADE DE PARCELAS, AVALIE SE O EMPRESTIMO PODE SER CONCEDIDO PELO BANCO. SABENDO QUE O VALOR MAXIMO DA PRESTACAO PODE SER ATÉ 30% DO VALOR DO SALARIO LIQUIDO (APOS EXCLUSAO DOS IMPOSTOS)
            TABELA DE IMPOSTOS
                < 5000  0%
                5000 < 10000 12.5%
                >= 10000 27,5%
        */
    }
}